[package]
name = "http2"
version = "1.0.0"
edition = "2018"

[dependencies]
ntex = { version = "0.6.5", features = ["tokio", "openssl"] }
openssl = { version = "0.10", features = ["v110", "vendored"] }
